/*
** Copyright (c) 2016, Xin YUAN, courses of Zhejiang University
** All rights reserved.
**
** This program is free software; you can redistribute it and/or
** modify it under the terms of the 2-Clause BSD License.
**
** Author contact information:
**   yxxinyuan@zju.edu.cn
**
*/

/*
This file contains FSA tables for regular expressions.
*/

////////////////////////////////////////////////////////////////////////////////

#include "PreComp.h"

#include "base/Fsa.h"
#include "base/FsaTable.h"

#include "ldf/regex/LdfRegexFsa.h"

////////////////////////////////////////////////////////////////////////////////
namespace GKC {
////////////////////////////////////////////////////////////////////////////////

// LdfRegexFsaTraits

BEGIN_FSA_TRAIT_CLASS(LdfRegexFsaTraits)
	FSA_BEGIN_STATE_TRANSITION(FSA_STATE_START)
		FSA_STATE_TRANSITION_ENTRY('\\', 2)
		FSA_STATE_TRANSITION_ENTRY('[', 3)
		FSA_STATE_TRANSITION_ENTRY(']', 4)
		FSA_STATE_TRANSITION_ENTRY('-', 5)
		FSA_STATE_TRANSITION_ENTRY('^', 6)
		FSA_STATE_TRANSITION_ENTRY('?', 7)
		FSA_STATE_TRANSITION_ENTRY('*', 8)
		FSA_STATE_TRANSITION_ENTRY('+', 9)
		FSA_STATE_TRANSITION_ENTRY('|', 10)
		FSA_STATE_TRANSITION_ENTRY('(', 11)
		FSA_STATE_TRANSITION_ENTRY(')', 12)
		FSA_STATE_TRANSITION_RANGE_ENTRY(0x21, 0x5B, 13)
		FSA_STATE_TRANSITION_RANGE_ENTRY(0x5D, 0xFFFFFFFF, 14)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(2)
		FSA_STATE_TRANSITION_ENTRY('\\', 15)
		FSA_STATE_TRANSITION_ENTRY('r', 16)
		FSA_STATE_TRANSITION_ENTRY('n', 17)
		FSA_STATE_TRANSITION_ENTRY('t', 18)
		FSA_STATE_TRANSITION_ENTRY('s', 19)
		FSA_STATE_TRANSITION_ENTRY('[', 20)
		FSA_STATE_TRANSITION_ENTRY(']', 21)
		FSA_STATE_TRANSITION_ENTRY('(', 22)
		FSA_STATE_TRANSITION_ENTRY(')', 23)
		FSA_STATE_TRANSITION_ENTRY('{', 24)
		FSA_STATE_TRANSITION_ENTRY('}', 25)
		FSA_STATE_TRANSITION_ENTRY('?', 26)
		FSA_STATE_TRANSITION_ENTRY('*', 27)
		FSA_STATE_TRANSITION_ENTRY('+', 28)
		FSA_STATE_TRANSITION_ENTRY('-', 29)
		FSA_STATE_TRANSITION_ENTRY('^', 30)
		FSA_STATE_TRANSITION_ENTRY('|', 31)
		FSA_STATE_TRANSITION_ENTRY('x', 32)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(3)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(4)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(5)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(6)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(7)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(8)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(9)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(10)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(11)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(12)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(13)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(14)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(15)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(16)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(17)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(18)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(19)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(20)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(21)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(22)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(23)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(24)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(25)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(26)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(27)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(28)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(29)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(30)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(31)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(32)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 33)
		FSA_STATE_TRANSITION_RANGE_ENTRY('A', 'F', 33)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'f', 33)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(33)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 34)
		FSA_STATE_TRANSITION_RANGE_ENTRY('A', 'F', 34)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'f', 34)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(34)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 35)
		FSA_STATE_TRANSITION_RANGE_ENTRY('A', 'F', 35)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'f', 35)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(35)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 36)
		FSA_STATE_TRANSITION_RANGE_ENTRY('A', 'F', 36)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'f', 36)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(36)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 37)
		FSA_STATE_TRANSITION_RANGE_ENTRY('A', 'F', 37)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'f', 37)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(37)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 38)
		FSA_STATE_TRANSITION_RANGE_ENTRY('A', 'F', 38)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'f', 38)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(38)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 39)
		FSA_STATE_TRANSITION_RANGE_ENTRY('A', 'F', 39)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'f', 39)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(39)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 40)
		FSA_STATE_TRANSITION_RANGE_ENTRY('A', 'F', 40)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'f', 40)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(40)
	FSA_END_STATE_TRANSITION()

	FSA_BEGIN_STATE_SET()
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, FSA_STATE_START, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 2, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 3, -19)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 4, -20)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 5, -21)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 6, -22)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 7, -23)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 8, -24)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 9, -25)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 10, -26)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 11, -27)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 12, -28)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 13, -29)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 14, -29)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 15, -1)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 16, -3)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 17, -4)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 18, -5)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 19, -6)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 20, -7)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 21, -8)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 22, -9)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 23, -10)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 24, -11)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 25, -12)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 26, -13)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 27, -14)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 28, -15)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 29, -16)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 30, -17)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 31, -18)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 32, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 33, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 34, -2)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 35, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 36, -2)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 37, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 38, -2)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 39, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 40, -2)
	FSA_END_STATE_SET()

	FSA_BEGIN_MATCH()
		FSA_MATCH_ENTRY(1)   //TK_CHAR_BACKSLASH
		FSA_MATCH_ENTRY(2)   //TK_CHAR_HEX
		FSA_MATCH_ENTRY(3)   //TK_CHAR_CR
		FSA_MATCH_ENTRY(4)   //TK_CHAR_LN
		FSA_MATCH_ENTRY(5)   //TK_CHAR_TAB
		FSA_MATCH_ENTRY(6)   //TK_CHAR_SPACE
		FSA_MATCH_ENTRY(7)   //TK_CHAR_LBRACKET
		FSA_MATCH_ENTRY(8)   //TK_CHAR_RBRACKET
		FSA_MATCH_ENTRY(9)   //TK_CHAR_LPAREN
		FSA_MATCH_ENTRY(10)  //TK_CHAR_RPAREN
		FSA_MATCH_ENTRY(11)  //TK_CHAR_LCURLY
		FSA_MATCH_ENTRY(12)  //TK_CHAR_RCURLY
		FSA_MATCH_ENTRY(13)  //TK_CHAR_QUESTION
		FSA_MATCH_ENTRY(14)  //TK_CHAR_STAR
		FSA_MATCH_ENTRY(15)  //TK_CHAR_PLUS
		FSA_MATCH_ENTRY(16)  //TK_CHAR_MINUS
		FSA_MATCH_ENTRY(17)  //TK_CHAR_UPARROW
		FSA_MATCH_ENTRY(18)  //TK_CHAR_VERT
		FSA_MATCH_ENTRY(19)  //TK_LBRACKET
		FSA_MATCH_ENTRY(20)  //TK_RBRACKET
		FSA_MATCH_ENTRY(21)  //TK_MINUS
		FSA_MATCH_ENTRY(22)  //TK_UPARROW
		FSA_MATCH_ENTRY(23)  //TK_QUESTION
		FSA_MATCH_ENTRY(24)  //TK_STAR
		FSA_MATCH_ENTRY(25)  //TK_PLUS
		FSA_MATCH_ENTRY(26)  //TK_VERT
		FSA_MATCH_ENTRY(27)  //TK_LPAREN
		FSA_MATCH_ENTRY(28)  //TK_RPAREN
		FSA_MATCH_ENTRY(29)  //TK_CHAR
	FSA_END_MATCH()
END_FSA_TRAIT_CLASS(LdfRegexFsaTraits)

////////////////////////////////////////////////////////////////////////////////
}
////////////////////////////////////////////////////////////////////////////////
