/*
** Copyright (c) 2016, Xin YUAN, courses of Zhejiang University
** All rights reserved.
**
** This program is free software; you can redistribute it and/or
** modify it under the terms of the 2-Clause BSD License.
**
** Author contact information:
**   yxxinyuan@zju.edu.cn
**
*/

/*
This file contains PDA tables for gra file.
*/

////////////////////////////////////////////////////////////////////////////////

#include "PreComp.h"

#include "_GkcCompiler.h"

#include "base/Pda.h"
#include "base/PdaTable.h"

#include "ldf/LdfGraPda.h"

////////////////////////////////////////////////////////////////////////////////
namespace GKC {
////////////////////////////////////////////////////////////////////////////////

// LdfGraPdaTraits

BEGIN_PDA_TRAIT_CLASS(LdfGraPdaTraits)
	PDA_BEGIN_STATE_TRANSITION(PDA_STATE_START)
		PDA_STATE_TRANSITION_ENTRY(101, 3)    //gra_def
		PDA_STATE_TRANSITION_ENTRY(4, 3)      //TK_SEP
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(3)
		PDA_STATE_TRANSITION_ENTRY(PDA_END_OF_EVENT, PDA_STATE_ACCEPTED)  //$
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(4)
		PDA_STATE_TRANSITION_ENTRY(102, 5)    //rule_block
		PDA_STATE_TRANSITION_ENTRY(6, 6)      //TK_MACRO
		PDA_STATE_TRANSITION_ENTRY(103, 22)   //rule
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(5)
		PDA_STATE_TRANSITION_ENTRY(PDA_END_OF_EVENT, -1)  //$
		PDA_STATE_TRANSITION_ENTRY(6, 6)      //TK_MACRO
		PDA_STATE_TRANSITION_ENTRY(103, 21)   //rule
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(6)
		PDA_STATE_TRANSITION_ENTRY(10, 7)     //TK_COLON
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(7)
		PDA_STATE_TRANSITION_ENTRY(104, 12)   //rule_right_block
		PDA_STATE_TRANSITION_ENTRY(106, 8)    //id_block
		PDA_STATE_TRANSITION_ENTRY(6, 17)     //TK_MACRO
		PDA_STATE_TRANSITION_ENTRY(7, 18)     //TK_TOKEN
		PDA_STATE_TRANSITION_ENTRY(107, 19)   //id
		PDA_STATE_TRANSITION_ENTRY(105, 20)   //rule_right
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(8)
		PDA_STATE_TRANSITION_ENTRY(8, 9)      //TK_LCURLY
		PDA_STATE_TRANSITION_ENTRY(107, 16)   //id
		PDA_STATE_TRANSITION_ENTRY(6, 17)     //TK_MACRO
		PDA_STATE_TRANSITION_ENTRY(7, 18)     //TK_TOKEN
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(9)
		PDA_STATE_TRANSITION_ENTRY(5, 10)     //TK_ACTION
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(10)
		PDA_STATE_TRANSITION_ENTRY(9, 11)     //TK_RCURLY
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(11)
		PDA_STATE_TRANSITION_ENTRY(11, -7)    //TK_VERT
		PDA_STATE_TRANSITION_ENTRY(12, -7)    //TK_SEMI
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(12)
		PDA_STATE_TRANSITION_ENTRY(11, 13)    //TK_VERT
		PDA_STATE_TRANSITION_ENTRY(12, 15)    //TK_SEMI
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(13)
		PDA_STATE_TRANSITION_ENTRY(106, 8)    //id_block
		PDA_STATE_TRANSITION_ENTRY(105, 14)   //rule_right
		PDA_STATE_TRANSITION_ENTRY(6, 17)     //TK_MACRO
		PDA_STATE_TRANSITION_ENTRY(7, 18)     //TK_TOKEN
		PDA_STATE_TRANSITION_ENTRY(107, 19)   //id
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(14)
		PDA_STATE_TRANSITION_ENTRY(11, -5)    //TK_VERT
		PDA_STATE_TRANSITION_ENTRY(12, -5)    //TK_SEMI
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(15)
		PDA_STATE_TRANSITION_ENTRY(PDA_END_OF_EVENT, -4)  //$
		PDA_STATE_TRANSITION_ENTRY(6, -4)     //TK_MACRO
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(16)
		PDA_STATE_TRANSITION_ENTRY(6, -8)     //TK_MACRO
		PDA_STATE_TRANSITION_ENTRY(7, -8)     //TK_TOKEN
		PDA_STATE_TRANSITION_ENTRY(8, -8)     //TK_LCURLY
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(17)
		PDA_STATE_TRANSITION_ENTRY(6, -11)    //TK_MACRO
		PDA_STATE_TRANSITION_ENTRY(7, -11)    //TK_TOKEN
		PDA_STATE_TRANSITION_ENTRY(8, -11)    //TK_LCURLY
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(18)
		PDA_STATE_TRANSITION_ENTRY(6, -10)    //TK_MACRO
		PDA_STATE_TRANSITION_ENTRY(7, -10)    //TK_TOKEN
		PDA_STATE_TRANSITION_ENTRY(8, -10)    //TK_LCURLY
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(19)
		PDA_STATE_TRANSITION_ENTRY(6, -9)     //TK_MACRO
		PDA_STATE_TRANSITION_ENTRY(7, -9)     //TK_TOKEN
		PDA_STATE_TRANSITION_ENTRY(8, -9)     //TK_LCURLY
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(20)
		PDA_STATE_TRANSITION_ENTRY(11, -6)    //TK_VERT
		PDA_STATE_TRANSITION_ENTRY(12, -6)    //TK_SEMI
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(21)
		PDA_STATE_TRANSITION_ENTRY(PDA_END_OF_EVENT, -2)  //$
		PDA_STATE_TRANSITION_ENTRY(6, -2)     //TK_MACRO
	PDA_END_STATE_TRANSITION()
	PDA_BEGIN_STATE_TRANSITION(22)
		PDA_STATE_TRANSITION_ENTRY(PDA_END_OF_EVENT, -3)  //$
		PDA_STATE_TRANSITION_ENTRY(6, -3)     //TK_MACRO
	PDA_END_STATE_TRANSITION()

	PDA_BEGIN_STATE_SET()
		PDA_STATE_SET_ENTRY(PDA_STATE_START)
		PDA_STATE_SET_ENTRY(3)
		PDA_STATE_SET_ENTRY(4)
		PDA_STATE_SET_ENTRY(5)
		PDA_STATE_SET_ENTRY(6)
		PDA_STATE_SET_ENTRY(7)
		PDA_STATE_SET_ENTRY(8)
		PDA_STATE_SET_ENTRY(9)
		PDA_STATE_SET_ENTRY(10)
		PDA_STATE_SET_ENTRY(11)
		PDA_STATE_SET_ENTRY(12)
		PDA_STATE_SET_ENTRY(13)
		PDA_STATE_SET_ENTRY(14)
		PDA_STATE_SET_ENTRY(15)
		PDA_STATE_SET_ENTRY(16)
		PDA_STATE_SET_ENTRY(17)
		PDA_STATE_SET_ENTRY(18)
		PDA_STATE_SET_ENTRY(19)
		PDA_STATE_SET_ENTRY(20)
		PDA_STATE_SET_ENTRY(21)
		PDA_STATE_SET_ENTRY(22)
	PDA_END_STATE_SET()

	PDA_BEGIN_RULE()
		PDA_RULE_ENTRY(101, 2)    // gra_def : TK_SEP rule_block
		PDA_RULE_ENTRY(102, 2)    // rule_block : rule_block rule
		PDA_RULE_ENTRY(102, 1)    // rule_block : rule
		PDA_RULE_ENTRY(103, 4)    // rule : TK_MACRO TK_COLON rule_right_block TK_SEMI
		PDA_RULE_ENTRY(104, 3)    // rule_right_block : rule_right_block TK_VERT rule_right
		PDA_RULE_ENTRY(104, 1)    // rule_right_block : rule_right
		PDA_RULE_ENTRY(105, 4)    // rule_right : id_block TK_LCURLY TK_ACTION TK_RCURLY
		PDA_RULE_ENTRY(106, 2)    // id_block : id_block id
		PDA_RULE_ENTRY(106, 1)    // id_block : id
		PDA_RULE_ENTRY(107, 1)    // id : TK_TOKEN
		PDA_RULE_ENTRY(107, 1)    // id : TK_MACRO
	PDA_END_RULE()
END_PDA_TRAIT_CLASS(LdfGraPdaTraits)

////////////////////////////////////////////////////////////////////////////////
}
////////////////////////////////////////////////////////////////////////////////
