/*
** Copyright (c) 2016, Xin YUAN, courses of Zhejiang University
** All rights reserved.
**
** This program is free software; you can redistribute it and/or
** modify it under the terms of the 2-Clause BSD License.
**
** Author contact information:
**   yxxinyuan@zju.edu.cn
**
*/

/*
This file contains FSA tables for lex & gra files.
*/

////////////////////////////////////////////////////////////////////////////////

#include "PreComp.h"

#include "base/Fsa.h"
#include "base/FsaTable.h"

#include "ldf/LdfFsa.h"

////////////////////////////////////////////////////////////////////////////////
namespace GKC {
////////////////////////////////////////////////////////////////////////////////

// LdfFsaTraits

BEGIN_FSA_TRAIT_CLASS(LdfFsaTraits)
	FSA_BEGIN_STATE_TRANSITION(FSA_STATE_START)
		FSA_STATE_TRANSITION_ENTRY('/', 2)
		FSA_STATE_TRANSITION_ENTRY(' ', 4)
		FSA_STATE_TRANSITION_ENTRY('\t', 4)
		FSA_STATE_TRANSITION_ENTRY('\r', 5)
		FSA_STATE_TRANSITION_ENTRY('\n', 7)
		FSA_STATE_TRANSITION_ENTRY('%', 8)
		FSA_STATE_TRANSITION_ENTRY('{', 10)
		FSA_STATE_TRANSITION_ENTRY('}', 11)
		FSA_STATE_TRANSITION_ENTRY('T', 12)
		FSA_STATE_TRANSITION_ENTRY('d', 16)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'c', 17)
		FSA_STATE_TRANSITION_RANGE_ENTRY('e', 'z', 17)
		FSA_STATE_TRANSITION_ENTRY(':', 21)
		FSA_STATE_TRANSITION_ENTRY('|', 22)
		FSA_STATE_TRANSITION_ENTRY(';', 23)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(2)
		FSA_STATE_TRANSITION_ENTRY('*', 3)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(3)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(4)
		FSA_STATE_TRANSITION_ENTRY(' ', 4)
		FSA_STATE_TRANSITION_ENTRY('\t', 4)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(5)
		FSA_STATE_TRANSITION_ENTRY('\n', 6)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(6)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(7)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(8)
		FSA_STATE_TRANSITION_ENTRY('%', 9)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(9)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(10)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(11)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(12)
		FSA_STATE_TRANSITION_ENTRY('K', 13)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(13)
		FSA_STATE_TRANSITION_ENTRY('_', 14)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(14)
		FSA_STATE_TRANSITION_RANGE_ENTRY('A', 'Z', 15)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(15)
		FSA_STATE_TRANSITION_RANGE_ENTRY('A', 'Z', 15)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 15)
		FSA_STATE_TRANSITION_ENTRY('_', 15)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(16)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'n', 17)
		FSA_STATE_TRANSITION_RANGE_ENTRY('p', 'z', 17)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 17)
		FSA_STATE_TRANSITION_ENTRY('_', 17)
		FSA_STATE_TRANSITION_ENTRY('o', 18)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(17)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'z', 17)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 17)
		FSA_STATE_TRANSITION_ENTRY('_', 17)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(18)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'z', 17)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 17)
		FSA_STATE_TRANSITION_ENTRY('_', 19)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(19)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'z', 20)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 17)
		FSA_STATE_TRANSITION_ENTRY('_', 17)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(20)
		FSA_STATE_TRANSITION_RANGE_ENTRY('a', 'z', 20)
		FSA_STATE_TRANSITION_RANGE_ENTRY('0', '9', 20)
		FSA_STATE_TRANSITION_ENTRY('_', 20)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(21)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(22)
	FSA_END_STATE_TRANSITION()
	FSA_BEGIN_STATE_TRANSITION(23)
	FSA_END_STATE_TRANSITION()

	FSA_BEGIN_STATE_SET()
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, FSA_STATE_START, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 2, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 3, -1)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 4, -2)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 5, -3)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 6, -3)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 7, -3)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 8, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 9, -4)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 10, -8)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 11, -9)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 12, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 13, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 14, 100)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 15, -7)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 16, -6)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 17, -6)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 18, -6)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 19, -6)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 20, -5)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 21, -10)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 22, -11)
		FSA_STATE_SET_ENTRY(FSA_STATE_STOP, 23, -12)
	FSA_END_STATE_SET()

	FSA_BEGIN_MATCH()
		FSA_MATCH_ENTRY(1)   //TK_COMMENT_START
		FSA_MATCH_ENTRY(2)   //TK_SPACE
		FSA_MATCH_ENTRY(3)   //TK_RETURN
		FSA_MATCH_ENTRY(4)   //TK_SEP
		FSA_MATCH_ENTRY(5)   //TK_ACTION
		FSA_MATCH_ENTRY(6)   //TK_MACRO
		FSA_MATCH_ENTRY(7)   //TK_TOKEN
		FSA_MATCH_ENTRY(8)   //TK_LCURLY
		FSA_MATCH_ENTRY(9)   //TK_RCURLY
		FSA_MATCH_ENTRY(10)  //TK_COLON
		FSA_MATCH_ENTRY(11)  //TK_VERT
		FSA_MATCH_ENTRY(12)  //TK_SEMI
	FSA_END_MATCH()
END_FSA_TRAIT_CLASS(LdfFsaTraits)

////////////////////////////////////////////////////////////////////////////////
}
////////////////////////////////////////////////////////////////////////////////
